========================
BaseGeometry class tests
========================

BaseGeomery class has two methods ``area(self)`` which raises exception
and ``integer_validator(self, name, value)`` which validates `value`
and raises exception

Calling area method.
::
	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry()
	>>> bg.area()
	Traceback (most recent call last):
        Exception: area() is not implemented

Calling area method with argument
::
	>>> bg.area(3)
	Traceback (most recent call last):
        TypeError: area() takes 1 positional argument but 2 were given

Calling integer_validator method with integer
::
	>>> bg.integer_validator('age', 3)

Calling integer_validator method with string
::
	>>> bg.integer_validator('age', '3')
	Traceback (most recent call last):
        TypeError: age must be an integer

Calling integer_validator method with tuple
::
        >>> bg.integer_validator('age', (3,))
        Traceback (most recent call last):
        TypeError: age must be an integer

Calling integer_validator method with list
::
        >>> bg.integer_validator('age', [3])
        Traceback (most recent call last):
        TypeError: age must be an integer

Calling integer_validator method with bool
::
        >>> bg.integer_validator('age', True)


Calling integer_validator method with set
::
        >>> bg.integer_validator('age', {2,3})
        Traceback (most recent call last):
        TypeError: age must be an integer


Calling integer_validator method with None
::
        >>> bg.integer_validator('age', None)
        Traceback (most recent call last):
        TypeError: age must be an integer

Calling integer_validator method with value zero
::
	>>> bg.integer_validator('age', 0)
	Traceback (most recent call last):
        ValueError: age must be greater than 0

Calling integer_validator with no arguments
::
	>>> bg.integer_validator()
	Traceback (most recent call last):
        TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Calling integer_validator with one argument
::
	>>> bg.integer_validator('age')
	Traceback (most recent call last):
        TypeError: integer_validator() missing 1 required positional argument: 'value'
